"use client";

import type { Metadata } from "next";
import "./globals.scss";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

import { useRouter, usePathname } from "next/navigation";

// export const metadata: Metadata = {
//     title: "shop'coozy",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const router = useRouter();
    const pathname = usePathname();

    const excludePaths = ["/login", "/register"];

    return (
        <html lang="en">
            <body>
                {!excludePaths.includes(pathname) && <Nav />}
                <main>{children}</main>
                {!excludePaths.includes(pathname) && <Footer />}
            </body>
        </html>
    );
}
